//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmaster3000App.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issues
    {
        public long Id { get; set; }
        public string BookID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public bool Returned { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
